### ISSUE TITLE
Multiple Plays per Turn

### ISSUE THREAD

**Issue by SydneyWells** [sugad21/NMahjong_sugad21_morana21#12]
If you draw from the wall and then discard fast enough, it stays your turn and you get to go again. 
Reason why this is an issue: you probably shouldn't get to play infinitely, for obvious reasons.

**Comment by morana21** [comment]
unable to replicate

**Comment by SydneyWells** [comment]
Okay that's fair. I'm not 100% how I made it happen in the first place.

**Comment by morana21** [comment]
Thanks for the feedback
