### ISSUE TITLE
Music keeps playing after exiting game

### ISSUE THREAD

**Issue by marcial21** [sugad21/NMahjong_sugad21_morana21#13]
Steps to Recreate
1. Launch application.
2. Start game.
3. Turn on volume
4. Exit game
5. Lock tablet.

N. Music continues to play while in the home screen and also when locking the tablet.

**Comment by sugad21** [comment]
This is a bug were not going to fix because the app is still running even though you press home.

**Comment by marcial21** [comment]
Acknowledged!
