### ISSUE TITLE
Game crashes when selecting the Wall 

### ISSUE THREAD

**Issue by gerylkvinoya** [sugad21/NMahjong_sugad21_morana21#6]
Step to Recreate:
1. run the game
2. click on a tile
3. click on wall

--
The game crashes and must restart. This is an issue because we're unable to start the game.

**Comment by sugad21** [comment]
resolved. game doesn't crash anymore.

**Comment by sugad21** [comment]
This was because the action and discard function gave null tiles.

**Comment by gerylkvinoya** [comment]
Confirm that is has been fixed
